INSERT INTO seats (id, trip_id, seat_number, is_booked)
VALUES
    (nextval('seat_id_seq'), 1, 1, false),
    (nextval('seat_id_seq'), 1, 2, false),
    (nextval('seat_id_seq'), 1, 3, true),
    (nextval('seat_id_seq'), 2, 1, true),
    (nextval('seat_id_seq'), 2, 2, false),
    (nextval('seat_id_seq'), 2, 3, false),
    (nextval('seat_id_seq'), 3, 1, true),
    (nextval('seat_id_seq'), 3, 2, false),
    (nextval('seat_id_seq'), 3, 3, true),
    (nextval('seat_id_seq'), 4, 1, false),
    (nextval('seat_id_seq'), 4, 2, false),
    (nextval('seat_id_seq'), 4, 3, true),
    (nextval('seat_id_seq'), 5, 1, false),
    (nextval('seat_id_seq'), 5, 2, true),
    (nextval('seat_id_seq'), 5, 3, false),
    (nextval('seat_id_seq'), 6, 1, true),
    (nextval('seat_id_seq'), 6, 2, false),
    (nextval('seat_id_seq'), 6, 3, true),
    (nextval('seat_id_seq'), 7, 1, false),
    (nextval('seat_id_seq'), 7, 2, false),
    (nextval('seat_id_seq'), 7, 3, true);
